### PR TITLE
Convert lat/lang to DD/MM/SS on boarding page

### LINKED ISSUE #450: Position should display as degree/minute/second - DDMMSS - lat/lon
On the boarding details page - aka #/boardings/view/60a5696793e5d06ad86dde58 - the latitude and longitude are displayed in decimal format. See the red circles below:
Screen Shot 2022-02-01 at 11 51 32 AM

This may be of help in converting the decimals to degrees/minutes/seconds.

https://stackoverflow.com/questions/2056750/lat-long-to-minutes-and-seconds

### PR DESCRIPTION
**Pull request by mmhuseynov**
## Related Issue

Fixes #450 

## Checklist:

- [ ] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [ ] I linked an issue in the previous section
- [ ] I have commented on the linked issue
- [ ] I was assigned the linked issue (not required)
- [ ] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)

### Before

image

### After

image

### CODE REVIEW

**Review by Sheeri — CHANGES_REQUESTED** [review]
The functionality works, however the display should be different. This is my fault, I did not provide the correct display in the ticket.

Degrees should have the ° symbol, minutes ' and seconds ". 
Additionally, seconds should be as precise as we can - no rounding, please. Currently it rounds to the nearest integer.

e.g.:
Latitude of -22.94300857939794 should show up as : 22° 56' 34.8282" S
Longitude of 14.08932132 should show up as: 14° 5' 21.555" E

(I am asking for clarification from a subject matter expert about whether or not we should have the +/- symbols too, even though -22 S is redundant (because S implies -), so there may be another change. I will let you know, but you can start on this.

**Review by Sheeri — CHANGES_REQUESTED** [review]
Something's not quite right - the calculations look correct, but the decimal place is always 0. For example, this boarding record on staging - https://ofishapp-hgflv.mongodbstitch.com/#/boardings/view/5eab8aa70e8b3df7af23307e has:
Latitude
-1.0905554291539992
Longitude
-85.91671960704237

Which calculate out to:
1° 5' 25.99954" S lat
85° 55' 0.19059" W lon

but on the local build of this, it comes out to
1° 5' 25.00" S lat
85° 55' 0.00" W lon

**Comment by mmhuseynov** [comment]
Seconds should be rounded to 2 decimal places.
image
So this coordinate should be calculated as: 1° 5' 26.00"

**Review by Sheeri — APPROVED** [review]
Perfect!

**Pull request merged**
