### PR TITLE
Agency admin default page #218

### LINKED ISSUE #218: Default Homepage for Agency Admins
For agency admins the default homepage upon logging in should be the agency dashboard (the /agency_charts/AGENCYNAME page - the page you get if you click 'Dashboard' -> AGENCYNAME).

### PR DESCRIPTION
**Pull request by RitikPandey1**
Fixed #218

### CODE REVIEW

**Comment by RitikPandey1** [comment]
@Sheeri @am-MongoDB , please review

**Review by Sheeri — APPROVED** [review]
@RitikPandey1 I built this and the agency page comes up first when I login as the agency admin. Great work!

**Comment by Sheeri** [comment]
Great work, merging!

**Comment by RitikPandey1** [comment]
> @RitikPandey1 I built this and the agency page comes up first when I login as the agency admin. Great work!

Thanks @Sheeri

**Pull request merged**
