### PR TITLE
filter & chart header UI enhancements

### LINKED ISSUE #17: Web: Skinning - Dashboard should look like this
https://mongodb.invisionapp.com/share/W2XD0U23F8H#/screens/418359755_Agency_Admin-Home

### PR DESCRIPTION
**Pull request by deveshchatuphale7**
## Related Issue

Fixes #17 

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [x] I have commented on the linked issue
- [x] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)

* **Optional: Add any explanations here** 
Modified CSS & HTML for filter-panel component. Also added classes to dashboard components from bootstrap & root.css   

* **Optional: Add any relevant screenshots here**

### CODE REVIEW

**Review by Sheeri — CHANGES_REQUESTED** [review]
Thanks for contributing! It looks like the number next to the filter icon is the number of available filters. This isn't your fault, it wasn't specified, but the number should be the number of filters actually being used. 
Screen Shot 2020-10-11 at 2 03 54 PM


Also, on my install I'm seeing broken images for the 'down arrow' next to the filters as well as the dates:
Screen Shot 2020-10-11 at 2 05 03 PM

Screen Shot 2020-10-11 at 2 05 30 PM

**Comment by deveshchatuphale7** [comment]
I have updated logic in filter-panel component to show count of applied filters. I am not sure why down arrow is broken, working fine at my end 

Screenshot_2020-10-12 O-FISH

Let me know if latest commit solves the issue.
Thank you

**Review by Sheeri — APPROVED** [review]

**Comment by Sheeri** [comment]
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is fantastic and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

**Comment by Sheeri** [comment]
Hi @deveshchatuphale7! 
We noticed you haven't claimed your digital MongoDB swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

**Comment by deveshchatuphale7** [comment]
> 
> 
> Hi @deveshchatuphale7!
> We noticed you haven't claimed your digital MongoDB swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

Sure! Thanks!

**Pull request merged**
