### PR TITLE
Added semicolon after risk to all languages, removed coloring from wo…

### LINKED ISSUE #22: Skinning - Boardings - Filter Selected should look like this
https://mongodb.invisionapp.com/share/W2XD0U23F8H#/screens/418359760_Agency_Admin-Search-Boardings_Filter_Entered

### PR DESCRIPTION
**Pull request by crowtech7**
Added semicolon after risk to all languages, removed coloring from words, updated font-size, weight and added "expand-more arrow" to each to match the mock picture

## Related Issue

Fixes #22 

## Checklist:

- [X] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [X] I linked an issue in the previous section
- [X] I have commented on the linked issue
- [X] I was assigned the linked issue (not required)
- [X] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)

* **Optional: Add any explanations here** 

* **Optional: Add any relevant screenshots here** 
Screen Shot 2020-10-08 at 4 22 26 PM

### CODE REVIEW

**Review by Sheeri — APPROVED** [review]
The TABLE.RISK text is used in more than just that place. For example, on the boardings page, it's used in the table of boardings:

Screen Shot 2020-10-09 at 1 49 53 PM

The other changes look great!

**Comment by crowtech7** [comment]
Would you like me to edit the semicolon and submit another PR?

**Comment by Sheeri** [comment]
@crowtech7 yes - you can edit the character out, do a git commit, and then a git push. Because the PR is still open, pushing the code will automatically add it to the existing PR.

**Comment by crowtech7** [comment]
Updated the changes and removed the semicolon from the languages

**Comment by Sheeri** [comment]
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

**Comment by Sheeri** [comment]
Hi @crowtech7! 
We noticed you haven't claimed your digital MongoDB swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

**Pull request merged**
