### PR TITLE
Global admin default home page  #217

### PR DESCRIPTION
**Pull request by RitikPandey1**

### CODE REVIEW

**Comment by RitikPandey1** [comment]
@am-MongoDB , please review

**Comment by Sheeri** [comment]
@RitikPandey1 Congrats on building your own instance of O-FISH - as you found out it's not easy! 

Thank you so much for this pull request. It's very important that the proper page appears when someone logs in.

We will complete a full review within 3 days.

**Review by Sheeri — CHANGES_REQUESTED** [review]
This is not a full review; however I noticed there are 2 files that have only whitespace changes - you can see this at https://github.com/WildAid/o-fish-web/pull/251/files:

src/components/dashboards/agencies-dashboard.component.js  has a line addition at line 57
and
src/config.js has a whitespace addition at line 4

Please remove the whitespace from those files and commit to this branch again - that way the only changes are the actual changes made to the functionality in src/components/login/login.component.js 

Thanks!

**Comment by RitikPandey1** [comment]
> This is not a full review; however I noticed there are 2 files that have only whitespace changes - you can see this at https://github.com/WildAid/o-fish-web/pull/251/files:
> 
> src/components/dashboards/agencies-dashboard.component.js has a line addition at line 57
> and
> src/config.js has a whitespace addition at line 4
> 
> Please remove the whitespace from those files and commit to this branch again - that way the only changes are the actual changes made to the functionality in src/components/login/login.component.js
> 
> Thanks!

@Sheeri  I removed whitespace from both files

**Comment by RitikPandey1** [comment]
@Sheeri As it take 3 days for complete review ,till then can I work on other issues ?

**Comment by Sheeri** [comment]
Hi @RitikPandey1 - good job on removing the whitespace. And yes, you can absolutely work on another issue while we review.

**Review by Sheeri — APPROVED** [review]

**Review by Sheeri — APPROVED** [review]
Built and tested the global administrator home page, as well as reviewed the code. It's good!

**Comment by Sheeri** [comment]
@RitikPandey1 Congratulations! Your code has been approved and is merged into the codebase.

Thanks so much for your great PR. I hope you will pick up another issue soon. :D

**Comment by RitikPandey1** [comment]
> Built and tested the global administrator home page, as well as reviewed the code. It's good!

Thanks @Sheeri, for your valuable feedback

**Comment by Sheeri** [comment]
Hi @RitikPandey1! 
We noticed you haven't claimed your digital MongoDB swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

**Comment by RitikPandey1** [comment]
Done 👍

**Pull request merged**
