### PR TITLE
fix authentication

### LINKED ISSUE #24: Web: Incorrectly logging in on 1st attempt
When logging in through the web app the app makes a failed login attempt and then tries again with the correct credentials. Should log in just once with the correct credentials.

### PR DESCRIPTION
**Pull request by zsobral**
- rehydrate correctly the user on page refresh
- use realm sdk to handle the authenticated user instead doing manually
- when a user hit a authenticated route will be prompted to login and after will redirect to that route

fix #24

### CODE REVIEW

**Comment by Sheeri** [comment]
zsobral this is great! the rehydrating especially is a bug that has been annoying for me. Our eng team will be reviewing the code in depth shortly, but they said your code and the refactoring you did looks really good.

**Comment by Sheeri** [comment]
@zsobral I'm particularly excited because this is the first community PR we have gotten for the O-FISH application. We'd love to give you a shout out on twitter and in our community forums, and see if we can send you some swag. If that sounds good to you, please connect with Ryan Quinn ryan.quinn@mongodb.com (developer relations team). Thanks!

**Comment by zsobral** [comment]
That is awesome! Thank you! 😄 

If is there some request changes or doubt about the PR, I'm open to discuss with the team.

**Comment by zsobral** [comment]
No, I don't mind.

**Pull request merged**
