### PR TITLE
Localize to Spanish #11

### LINKED ISSUE #11: Localize to Spanish

### PR DESCRIPTION
**Pull request by ismaeldcom**
## Related Issue
Fixes #11 

## Checklist:

- [x] I have read the [contributor's guide](https://wildaid.github.io/contribute/index.html).
- [x] I linked an issue in the previous section
- [ ] I have commented on the linked issue
- [ ] I was assigned the linked issue (not required)
- [x] I have tested the change to the best of my ability against the [sandbox](https://wildaid.github.io/contribute/sandbox.html) or a [local build](https://wildaid.github.io/build).

Optional items:

- [ ] My change adds new text and requires a change to translations.
- [ ] My change requires a change to the documentation.
- [ ] I have submitted a PR to the [documentation repo](https://github.com/WildAid/wildaid.github.io).
- [ ] I was not able to test... (explain below, e.g. you did not have permissions to test a specific feature)
- [ ] This change depends O-FISH Realm repository changes (explain below)

I have a small doubt with one word, I need more context to translate it properly. Is the TABLE.CITATIONS, do you mean subpoenas, references or mentions?

Cheers

### CODE REVIEW

**Review by Sheeri — CHANGES_REQUESTED** [review]
Looks great!

I spot-checked the login page, agency page, boardings/vessel/crew pages (overview and details page).

There are some missing translations, which are not your fault, they were not included in the file itself (the fields themselves aren't looking for translations):
Screen Shot 2020-10-04 at 10 04 19 AM

Can you add in the translations, under the TABLE group (starting line 168), for:
PERMIT_NUMBERS
FLAG_STATES
HOME_PORTS
CAPTAINS

Otherwise, the screens look great! Screen Shot 2020-10-04 at 9 57 21 AM

**Comment by ismaeldcom** [comment]
Sure I just push them :)

**Comment by Sheeri** [comment]
I realize I didn't answer your question, @ismaeldcom:
"I have a small doubt with one word, I need more context to translate it properly. Is the TABLE.CITATIONS, do you mean subpoenas, references or mentions?"

A citation is a written violation, like a parking ticket or speeding ticket.

**Comment by ismaeldcom** [comment]
Ok, is what I thought them

**Review by Sheeri — APPROVED** [review]
Perfect!

**Comment by Sheeri** [comment]
Congratulations! 🎉 🙌 🎆 ㊗️ 

This PR is great and has been merged into the code. Thanks so much for contributing! If you'd like, you can request to work on another issue. We really appreciate your effort!

**Comment by Sheeri** [comment]
@ismaeldcom Another issue that is similar that you might be interested in is https://github.com/WildAid/o-fish-android/issues/28 - https://github.com/WildAid/o-fish-android/blob/main/LOCALIZATION.md has instructions on how to localize the files, and if you cannot build android I am happy to test it for you.

**Comment by ismaeldcom** [comment]
Ok @Sheeri I'll take a look to it soon.

**Comment by Sheeri** [comment]
Hi @ismaeldcom! 
We noticed you haven't claimed your digital MongoDB swag. To claim your O-FISH badge, head on over to the [MongoDB Community forums](https://developer.mongodb.com/community/forums/t/open-source-contributors-pick-up-your-badges-here/10167/9), login, and reply - making sure to link to this PR.

**Pull request merged**
